// Bridge between the Pinpoint UI (renderer) and the main process.
const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (cb) => {
  const fn = (_e, data) => cb(data);
  ipcRenderer.on(channel, fn);
  return () => ipcRenderer.removeListener(channel, fn);
};

contextBridge.exposeInMainWorld('pinpoint', {
  platform: process.platform,
  onFullscreen: on('window:fullscreen'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
  detectAgents: () => ipcRenderer.invoke('agents:detect'),
  modelCatalog: () => ipcRenderer.invoke('agents:models'),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  openPath: (p) => ipcRenderer.invoke('shell:openPath', p),
  capture: (webContentsId, rect) => ipcRenderer.invoke('capture', { webContentsId, rect }),
  runAgent: (args) => ipcRenderer.invoke('agent:run', args),
  cancelAgent: (runId) => ipcRenderer.invoke('agent:cancel', runId),
  steerAgent: (args) => ipcRenderer.invoke('agent:steer', args),
  nudgeAgent: (runId) => ipcRenderer.invoke('agent:nudge', runId),
  openFile: (rel, line) => ipcRenderer.invoke('shell:openFile', { rel, line }),
  runDiff: (runId) => ipcRenderer.invoke('run:diff', runId),
  revertRun: (runId, paths, force) => ipcRenderer.invoke('run:revert', { runId, paths, force }),
  applyRun: (runId) => ipcRenderer.invoke('run:apply', runId),
  forceState: (webContentsId, selector, classes) => ipcRenderer.invoke('page:force', { webContentsId, selector, classes }),
  emulate: (webContentsId, env) => ipcRenderer.invoke('page:emulate', { webContentsId, ...env }),
  designSystem: () => ipcRenderer.invoke('design:system'),
  componentUsage: (name) => ipcRenderer.invoke('design:usage', name),
  a11ySource: () => ipcRenderer.invoke('a11y:source'),
  prewarmRoutes: (list, partition) => ipcRenderer.invoke('routes:prewarm', { list, partition }),
  tailwindCss: (classes) => ipcRenderer.invoke('tailwind:css', classes),
  measureBuild: (pageUrl) => ipcRenderer.invoke('build:measure', pageUrl),
  replay: (webContentsId, steps) => ipcRenderer.invoke('page:replay', { webContentsId, steps }),
  startStorybook: (name) => ipcRenderer.invoke('story:start', name),
  matchedRules: (webContentsId, uid) => ipcRenderer.invoke('page:rules', { webContentsId, uid }),
  setAnimationRate: (webContentsId, rate) => ipcRenderer.invoke('page:animation', { webContentsId, rate }),
  setNetwork: (webContentsId, mode) => ipcRenderer.invoke('page:network', { webContentsId, mode }),
  findStory: (name) => ipcRenderer.invoke('story:find', name),
  listPins: () => ipcRenderer.invoke('pins:list'),
  addPin: (pin) => ipcRenderer.invoke('pins:add', pin),
  checkPins: () => ipcRenderer.invoke('pins:check'),
  pinImages: (id) => ipcRenderer.invoke('pins:images', id),
  acceptPin: (id) => ipcRenderer.invoke('pins:accept', id),
  removePin: (id) => ipcRenderer.invoke('pins:remove', id),
  saveHandoff: (name, data) => ipcRenderer.invoke('handoff:save', { name, data }),
  openHandoff: () => ipcRenderer.invoke('handoff:open'),
  handoffIssue: (args) => ipcRenderer.invoke('handoff:issue', args),
  listChats: () => ipcRenderer.invoke('chats:list'),
  loadChat: (id) => ipcRenderer.invoke('chats:load', id),
  saveChat: (chat) => ipcRenderer.invoke('chats:save', chat),
  deleteChat: (id) => ipcRenderer.invoke('chats:delete', id),
  readDesign: () => ipcRenderer.invoke('design:read'),
  writeDesign: (content) => ipcRenderer.invoke('design:write', content),
  readMemory: () => ipcRenderer.invoke('memory:read'),
  writeMemory: (items) => ipcRenderer.invoke('memory:write', items),
  listRoutes: () => ipcRenderer.invoke('routes:list'),
  resolveSourceMap: (frame) => ipcRenderer.invoke('sourcemap:resolve', frame),
  onNetworkError: on('page:network'),
  onNewTab: on('browser:new-tab'),
  instantPlan: (annotation) => ipcRenderer.invoke('instant:plan', annotation),
  instantApply: (runId, annotation) => ipcRenderer.invoke('instant:apply', { runId, annotation }),
  listComponents: () => ipcRenderer.invoke('components:list'),
  readProfiles: () => ipcRenderer.invoke('profiles:read'),
  writeProfiles: (list) => ipcRenderer.invoke('profiles:write', list),
  applyProfile: (webContentsId, settings) => ipcRenderer.invoke('page:profile', { webContentsId, ...settings }),
  enginesStatus: () => ipcRenderer.invoke('engines:status'),
  enginesInstall: () => ipcRenderer.invoke('engines:install'),
  onEnginesProgress: on('engines:progress'),
  enginesShoot: (args) => ipcRenderer.invoke('engines:shoot', args),
  bgBlocker: () => ipcRenderer.invoke('bg:blocker'),
  bgStart: (args) => ipcRenderer.invoke('bg:start', args),
  bgDiff: (id) => ipcRenderer.invoke('bg:diff', id),
  bgShot: (id) => ipcRenderer.invoke('bg:shot', id),
  bgApply: (args) => ipcRenderer.invoke('bg:apply', args),
  bgDiscard: (id) => ipcRenderer.invoke('bg:discard', id),
  onBgEvent: on('bg:event'),
  updateState: () => ipcRenderer.invoke('update:state'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  termShells: () => ipcRenderer.invoke('term:shells'),
  termList: () => ipcRenderer.invoke('term:list'),
  termOpen: (opts) => ipcRenderer.invoke('term:open', opts),
  termAttach: (id) => ipcRenderer.invoke('term:attach', id),
  termWrite: (id, data) => ipcRenderer.send('term:write', { id, data }),
  termResize: (id, cols, rows) => ipcRenderer.send('term:resize', { id, cols, rows }),
  termClose: (id) => ipcRenderer.send('term:close', id),
  onTermData: on('term:data'),
  onTermExit: on('term:exit'),
  onUpdateState: on('update:state'),
  gitStatus: () => ipcRenderer.invoke('git:status'),
  gitInit: () => ipcRenderer.invoke('git:init'),
  gitBranch: (hint) => ipcRenderer.invoke('git:branch', hint),
  gitCommitRun: (runId) => ipcRenderer.invoke('git:commitRun', runId),
  gitCommitAll: (message) => ipcRenderer.invoke('git:commitAll', message),
  gitOpenPR: (args) => ipcRenderer.invoke('git:pr', args),
  saveShot: (runId, name, dataUrl) => ipcRenderer.invoke('run:saveShot', { runId, name, dataUrl }),
  runShots: (runId) => ipcRenderer.invoke('run:shots', runId),
  onAgentEvent: on('agent:event'),
  startDev: (command) => ipcRenderer.invoke('dev:start', { command }),
  detectDev: () => ipcRenderer.invoke('dev:detect'),
  stopDev: () => ipcRenderer.invoke('dev:stop'),
  onDevEvent: on('dev:event'),
});
